apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-memory-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-memory-demo
  template:
    metadata:
      labels:
        app: cpu-memory-demo
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        command: ["stress"]
        args: ["--cpu", "1", "--timeout", "3600s", "--vm", "1", "--vm-bytes", "50M"]
