version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts:/scripts:ro

  traffic-generator:
    build:
      context: .
      dockerfile: Dockerfile.traffic-generator
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    volumes:
      - ./scripts:/scripts:ro
