name 'icinga2_monitor'
maintainer 'Saurabh Hirani'
maintainer_email 'saurabh.hirani@gmail.com'
description 'Installs/Configures icinga2'
long_description 'Installs/Configures icinga2'
version '0.1.0'

depends 'apache2', '3.2.0'
depends 'php', '1.8.0'
depends 'icinga2', '2.7.0' 
depends 'chef-solo-search' 
depends 'apt'
